@apiurl = http://localhost:7000

### ====== CHECK ONLINE ===========
GET {{apiurl}}


### ====== POST MESSAGE ===========
POST {{apiurl}}/send-message
content-type: application/json

{
    "type": "text",
    "waID": "5516993647115",
    "text": "você recebeu essa msg?"
}


### ====== POST MESSAGE ===========
POST {{apiurl}}/send-message
content-type: application/json

{
    "type": "list",
    "waID": "5516993259257",
    "text": "Titulo do Header",
    "list_items": [
        {"id": "id_1", "title":"Titulo 1"},
        {"id": "id_2", "title":"Titulo 2"}
    ]
}